name: run-macho
on: workflow_dispatch
jobs:
  run:
    runs-on: macos-14
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v4
      - name: run it
        run: |
          chmod +x real_macho_1_full.bin
          python3 patch.py
